### ISSUE TITLE
Worum geht’s denn dabei

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#1]
... 
https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/blob/4b8c8c9700488d9c6a3484ad2360f55e45feab3a/bin/grabber.pl#L66

Hab ich das schon gefixt?

**Comment by mschlenstedt** [comment]
Ja. Der Code im Repo ist nicht aktuell.
