### ISSUE TITLE
Request to implement zoned_clean, GoTO, spot

### ISSUE THREAD

**Issue by begunrom** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#11]
I would appriciate if you could implement the zoned_clean(),goto(x_coord, y_coord) & spot() function, so a quick clean of the most dirt spots can be done. Cleaning the whole ground floor takes over 1 hour, while cleaning the always dirty spots would only take 15 minutes.
If there would be a custom function provided by loxberry, where i could specify the combination of goto, spot and zoned_clean to be executed in sequence that would be ideal, but I already would be happy if the individual funstions would exist.

**Comment by mschlenstedt** [comment]
This is quite complicated and I personally do not need this feature. I cannot promise to implement it in the future. Sorry.

**Comment by nolamesu** [comment]
@begunrom
Meanwhile spot()-Cleaning is supported. If you use one of the gen2 vacuums with the actual firmware supporting rooms (e.g. S5 with firmware 2008 or newer) you can trigger a room cleaning (or cleaning a list of rooms).

For doing so you need to configure the command of your virtual output in LoxoneConfig as follows:
`/plugins/mirobot2lox-ng/sendcmd.cgi?command=segment_clean&option=[17]&robot=1&debug=0 `
As `option` you can pass a list of room numbers (in my example `[17]`). You could also write `[16,17]` for cleaning of two rooms.

The mapping of rooms to room numbers you can get with the `get_room_mapping` command. Simply visit this url in your browser:
`http://loxberry/plugins/mirobot2lox-ng/sendcmd.cgi?command=get_room_mapping&robot=1&debug=0`

To clean zones you need to pass the coordinates. How this is done is described here:
https://www.loxwiki.eu/display/LOXBERRY/MiRobot2Lox-NG#MiRobot2LoxNG-Koordinatenf%C3%BCrZonenreinigungermitteln

Propably this already satisfies your needs.

Regards,
Tim

**Comment by mschlenstedt** [comment]
Since it worked now, I will close thos issue. Please reopen if any further ehlp is needed.
