### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by pavelsnajdr** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#12]
Hi Michael,
I made the translation into Czech. Please can you implement new language to the plugin?
Thank you,
Pavel

**Comment by pavelsnajdr** [comment]
translation file....
[language_cs.zip](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/2717519/language_cs.zip)

**Comment by mschlenstedt** [comment]
Thanks a lot! I will include it in the next release.
