### ISSUE TITLE
Broken pipe Python MIIO tools installation failed! V1.0.1

### ISSUE THREAD

**Issue by MS061981** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#14]
Installation des Plugins bricht ab. Loxberry wurde schon neu aufgesetzt.

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7kpmxhk3/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8pthm0gv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-7kpmxhk3/cffi/ yes: standard output: Broken pipe Python MIIO tools installation failed!

[8S6aQhMIRo.txt](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/2868743/8S6aQhMIRo.txt)

**Comment by mschlenstedt** [comment]
Vermutlich identisch mit #19 Bitte mit nächstem Release 1.0.5 testen.

**Comment by Scolair** [comment]
Still problem with Release 1.0.5 :/ - > Broken pipe Python MIIO tools installation failed!
gcc libffi-dev libssl-dev python3-dev was installed correctly ...

**Comment by mschlenstedt** [comment]
Have you tested this in a fresh loxberry or habe you done any manual things in your loxberry (e. g. Kernel Updates, apt-get upgrade, etc. )?

I will test it on a fresh LicBerry tonight, but I am pretty sure that it worked last time on a fresh LB.

**Comment by Scolair** [comment]
Yes I was test on the fresh loxberry from this link https://loxberry.kim.bz/latest.zip  on the HW (Pi 3 Model B+ )

**Comment by mschlenstedt** [comment]
Should be fixed.
