### ISSUE TITLE
Ein Fehler trat auf, das Plugin konnte nicht installiert werden.

### ISSUE THREAD

**Issue by maxweissboeck** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#15]
Situation:
- komplett neu aufgesetzter loxberry
- loxberry version 1.4.0.3
- plugin zum ersten mal installiert
- Fehler in der Console

compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Failed building wheel for cryptography
Running setup.py clean for cryptography
Failed to build cryptography
Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
yes: standard output: Broken pipe
 WARNING: Python MIIO tools installation failed! The plugin will not work without.
 WARNING: Giving up.
08.03.2019 09:09:51 CRITICAL: Fehler während der Script-Installation, die Installation wurde beendet.
removed '/tmp/SgqitINjgo.zip'

**Comment by maxweissboeck** [comment]
Braucht das Plugin ein paar Voraussetzungen, wegen der cryptography?

Danke Max

**Comment by mschlenstedt** [comment]
Mmhh, muss ich mal testen. Er holt sich immer die aktuellsten Python-Pakete. Vielleicht ist da aktuell auch gerade irgendein Fehler drin.

**Comment by mschlenstedt** [comment]
Hallo Max,

es müssen folgende Pakete installiert sein (die eigentlich automatisch installiert werden):

```
ccrypt
liburi-encode-perl
python3-pip
```

Wenn die Pakete drauf sind, dann bitte mal zusätzlich noch folgendes nachinstallieren:

```apt-get install libffi-dev libssl-dev```

**Comment by qaldak** [comment]
Habe genau dasselbe Problem. Habe die erwähnten Pakete zwar installiert, aber das Plugin kann noch immer nicht installiert werden.

```
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-armv7l-3.5/_openssl.c -o build/temp.linux-armv7l-3.5/build/temp.linux-armv7l-3.5/_openssl.o -Wconversion -Wno-error=sign-conversion
build/temp.linux-armv7l-3.5/_openssl.c:22:24: fatal error: pyconfig.h: No such file or directory
# include 
^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Failed building wheel for cryptography
Running setup.py clean for cryptography
Failed to build cryptography
Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
yes: standard output: Broken pipe
 WARNING: Python MIIO tools installation failed! The plugin will not work without.
 WARNING: Giving up.
15.04.2019 21:22:16 CRITICAL: Fehler während der Script-Installation, die Installation wurde beendet.
removed '/tmp/DIgXbBGeiw.zip'
```

Log [8S6aQhMIRo.txt](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/3081793/8S6aQhMIRo.txt)

**Comment by mschlenstedt** [comment]
Vermutlich identisch mit #19 Bitte mit nächstem Release 1.0.5 testen.

**Comment by mschlenstedt** [comment]
Should be fixed.
