### ISSUE TITLE
msudp_send_mem verwenden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#2]
https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/blob/4b8c8c9700488d9c6a3484ad2360f55e45feab3a/bin/grabber.pl#L153

**Comment by mschlenstedt** [comment]
Bereits implementiert. Code in GIT nicht aktuell.
