### ISSUE TITLE
Installationsproblem mit v 1.0.5 auf LB 1.4.2.2 - Python MIIO Tools Installation failed 

### ISSUE THREAD

**Issue by Stonelink77** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#21]
Danke für Unterstützung bei folgendem Installationsabbruch:

Hier die Fehlermeldung im Verlauf:
***********

OK: Python Setuptools installed successfully.
INFO: Start installing Python MIIO tools...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting python-miio
Downloading https://files.pythonhosted.org/packa...3-none-any.whl (160kB)
ERROR: Package 'python-miio' requires a different Python: 3.5.3 not in '>=3.6'
yes: standard output: Broken pipe
WARNING: Python MIIO tools installation failed! The plugin will not work without.
WARNING: Giving up.
09.11.2019 23:48:56 CRITICAL: Fehler während der Script-Installation, die Installation wurde beendet.
removed '/tmp/ewFGAxRUYC.zip'

****

Neu aufgesetzter LB mit paar Plugins drauf wie Smartmeter, Weather, backup Miniserver, backup Loxberry, ebusd,
Sollte an sich funktionieren.

Danke für Support und ggf Update des fehlerhaften Codes o.ä. 
Scheint da ja ein Problem bei der Version 3.5.3 vs. 3.6 zu geben...

Merci

**Comment by mschlenstedt** [comment]
Du musst auf LB 2.0 updaten.

**Comment by Stonelink77** [comment]
Danke für die Info.

LB 2.0 hatte ich schon 2x installiert, da haben andere Plugins nicht mit funktioniert...
Vor allem das Smartmeter Plugin hat nicht korrekt gearbeitet ... das liegt ja auch in Deiner Hand... werde mich nochmal damit beschäftigen...

Keine Chance den miRobot auf 1.4.2.2 noch zum laufen zu bringen? 
Meine bevor es das Update auf LB 2.0 gab war das MiRobot Plugin doch auch schon da... könnte man nicht eine ältere Version installieren?

Beste Grüße und weiter viel Erfolg - macht Spaß Teil der Community zu sein!

Martin

**Comment by mschlenstedt** [comment]
Leider nein. Liegt aber nicht an Plugin.  Das Plugin nutzt eine Python Software, um die Sauger zu steuern. Und das braucht eine aktuelle Pythoninstallation, die es nur auf LB2 gibt. Deswegen bringt es auch nichts eine alte Pluginversion zu installieren.

**Comment by Stonelink77** [comment]
Ok, verstehe ...

Läuft denn der Smartmeter Plugin „Stable“ auf LB 2 oder hast du von Problemen erfahren? Habe selbst einen Volkszähler Lesekopf und einen itron Zähler.

VG und Danke Dir Martin

**Comment by Stonelink77** [comment]
Hallo Michael,

ermutigt durch Deine Mails und nachdem ich mit sehr viel Mühe das Loxberry
Backup Plugin ans Laufen bekommen habe und eine ddl Sicherung erfolgreich
gespeichert wurde, habe ich nochmal einen Versuch mit LB Update auf 2.003
gewagt.

Hat erfolgreich geklappt, MiRobot konnte ich dann problemlos installieren
und muss es jetzt mit der Konfiguration noch schaffen...


- Smartmeter läuft auch weiter - Gott sei Dank

- Weather 4 Lox ist kurz mal ausgestiegen also war in der App nicht mehr
da... habe das im Forum nicht ganz nachvollzogen was Du und Svethy
geschrieben hattet mit incur gehen und DNS 2 freilassen... wird wohl
irgendwo in der Config sein
habe jedenfalls einmal visu verwenden deaktiviert und gespeichert und
danach wieder aktiviert und in den MS gespeichert und dann ging es wieder

- mit dem Loxberry Backup tue ich mich noch sehr schwer... habe einen 30 GB
USB Stick am Pi und es gibt bislang keine vernünftige Anleitung für
Anfänger wie mich...

habe bereits Stunden im Web gelesen und was probiert ...die fstab editiert
und was sonst so aus den verschiedenen Seiten steht aber das ist noch zäh
wie Kaugummi.

Glaube da könnte Chrisitan F. noch sehr helfen wenn er paar Dinge
klarstellt auf seiner Plugin seite bzw. gleich in das Plugin gewisse
Optionen für Anfänger einbaut, so dass der Loxberry den Stick übernimmt und
mountet wenn der user das legitimiert (z.B. weil er sonst keinen Dunst
hat...) Gab da ja im Forum erste Tendenzen und nachfragen was da da tun
müsste -- ich würde das sehr begrüßen.

Bei Loxberry soll ja alles möglichst selbsterklärend und einach sein... und
das ist es da aktuell m.E. ohne Linux Kenntnisse nicht... und nach ner
Anleitung was abtippen funktioniert auch nicht wirklich. und wenn dann noch
das Thema NAS Laufwerk dazu kommt... oje

Fängt mit der Formatierung des USB Sticks an...
Standard ist XFAT... da liest man dann im Forum geh auf NTFS
das macht man dann und formatiert den Stick... und stellt dann fest mit
NTFS hat der Stick nur noch Leserechte ... man müsste wohl Zusatzsoftware
laden... das traut man sich wieder nicht, man könnte ja den loxberry
crashen... und Ahnung hat man wenig

Also dann doch Variante 3 und exfat`? wie das dann formatieren...

usw,,, usw,,,

Naja ist nicht Deine Baustelle aber ihr tauscht Euch sicher aus... werde
Christian F. auch schreiben, glaube das Plugin ist eins der wichtigsten für
alle LB Nutzer. Da sollte maximale Einfachheit bei der Einrichtung
herrschen. und USB Stick ist eine günstige und einfache schnelle Lösung...


Also sei lieb gegrüßt

Bemühe mich weiter mein Wissen aufzutanken und konnte auch schon dem Ein
oder Anderen helfen...

Ciao Martin

P.S.: 1995/96 in Delmenhorst beim Bund gewesen mit mir? Nachschub?

**Comment by mschlenstedt** [comment]
In LoxBerry 2.0 muss der Stick auch mit NTFS problemlos erkannt werden. Wenn er nicht mit Schreibrechten gemountet wird, dann liegt das meist an einem nicht sauberen Dateisystem. Formatiere den Stick mal unter Windows und werfe den Stick dann sauber aus, bevor Du ihn abziehst.

**Comment by Stonelink77** [comment]
Danke Michael,

Hat mir wieder sehr weitergeholfen die Info... Christian hatte im Forum auch später geschrieben..,

Stick und Ddz manuell klappt jetzt bereits...
RSync beobachte ich mal brauche noch eine Idee welche Frequenz man dafür ansetzen sollte...

Ansonsten versuche ich gerade dem Roborock den Token zu entlocken... dauert mit dem iPhone Backup erstellen
Hatte bislang alles in iCloud oder verschlüsselt ...

Nunja kommt Zeit kommt Rat.
Wünsche Dir noch einen schönen Tag!

VG Martin
