### ISSUE TITLE
Andere Devices als vacuum unterstützen

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#24]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/168084-plugin-mirobot2lox-ng-xiaomi-vacuum-robots?p=257364#post257364

**Comment by fs79** [comment]
Hab gerade eine Version erstellt da kann man das Device bei den Settings einfügen.
Getestet mit Staubsaugern, das Freifeld macht aber keine Syntaxprüfung daher alle Geräte die miiocli unterstützt möglich.
Daher einfach ausprobieren.

**Comment by mschlenstedt** [comment]
Mit V1.20 nun (endlich) implementiert.
