### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by TestMyLox** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#3]
<INFO> Installation as root user started.
<INFO> Start installing Python Setuptools...
/tmp/uploads/MX5aYpToZI/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.0/preroot.sh: line 59: pip3: command not found
yes: standard output: Broken pipe
/tmp/uploads/MX5aYpToZI/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.0/preroot.sh: line 61: pip3: command not found
<WARNING> Python Setuptools installation failed! The plugin will not work without.
<WARNING> Giving up.
<FAIL> Fehler wÃ¤hrend der Script-Installation, die Installation wurde beendet.
[error log.log](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/2386050/error.log.log)

**Comment by mschlenstedt** [comment]
Thanks. pip3 package is missing.

**Comment by mschlenstedt** [comment]
Please try Version 0.5.1 - it should be fixed.
