### ISSUE TITLE
Sending status doesn't work because of python3.5 deprecation warning

### ISSUE THREAD

**Issue by Gagi2k** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#30]
It looks like the crypthography package used by the python3-miio package is deprecated for python3.5.

When using the /opt/loxberry/bin/plugins/mirobot2lox-ng/mirobo_wrapper.sh to fetch the latest status always the following warning is printed:

/usr/local/lib/python3.5/dist-packages/miio/protocol.py:24: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.

This makes the JSON parsing to fail and no status is send to loxone.

As updating python3 (which is installed using apt), might not be the best option, i workaround this problem by adding the following env variable to the mirobo_wrapper.sh script.

PYTHONWARNINGS=ignore

**Comment by nori0077** [comment]
Hello. Is it possible send a screenshot about the additional line at the script?

**Comment by mschlenstedt** [comment]
I will add the line, but wonder why you have Python 3.5 installed. Latest LoxBerry ships with Python 3.7, and there is no warning regarding crypthographic module...

**Comment by Gagi2k** [comment]
Good point, i just relalized that my VM is still on stretch although it's running Loxberry v2.

No need to update it in this case, it's clearly a problem on my end.
