### ISSUE TITLE
Xiaomi IMILAB V1 integration

### ISSUE THREAD

**Issue by omegasxxi** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#36]
Hello,
Is it possible to include support for the IMILAB V1 robot?

Thanks
Oscar

**Comment by mschlenstedt** [comment]
Ask here: https://github.com/rytilahti/python-miio

If miio supports the device, the plugin can be enhanced. We do not develope the miio software, just build a plugin around.
