### ISSUE TITLE
token_extractor problem

### ISSUE THREAD

**Issue by viperdriver2000** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#38]
hi,
i try the plugin and try to extract the token.
i had the following problems.

> loxberry@loxberry:~ $ python3 ~/bin/plugins/mirobot2lox-ng/token_extractor.py
> Traceback (most recent call last):
>   File "/opt/loxberry/bin/plugins/mirobot2lox-ng/token_extractor.py", line 9, in <module>
>     from Crypto.Cipher import ARC4
> ModuleNotFoundError: No module named 'Crypto'

i fix this with
> loxberry@loxberry:~ $ pip install pycrypto
> Defaulting to user installation because normal site-packages is not writeable
> Collecting pycrypto
>   Downloading pycrypto-2.6.1.tar.gz (446 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.2/446.2 KB 5.8 MB/s eta > 0:00:00
>   Preparing metadata (setup.py) ... done
> Building wheels for collected packages: pycrypto
>   Building wheel for pycrypto (setup.py) ... done
>   Created wheel for pycrypto: filename=pycrypto-2.6.1-cp37-cp37m-linux_x86_64.whl size=493245 > sha256=8160bb785a7966a4e3a13b53b2813b0f9573bb7ca26f92df73aa30360b513962
>   Stored in directory: /opt/loxberry/.cache/pip/wheels/cf/85/ba/bbd7c96add459de7598fb424e5ff2309baf2095c844ac0f191
> Successfully built pycrypto
> Installing collected packages: pycrypto
> Successfully installed pycrypto-2.6.1

now i have a new problem
> loxberry@loxberry:~ $ python3 ~/bin/plugins/mirobot2lox-ng/token_extractor.py
> Traceback (most recent call last):
>   File "/opt/loxberry/bin/plugins/mirobot2lox-ng/token_extractor.py", line 9, in <module>
>     from Crypto.Cipher import ARC4
>   File "/opt/loxberry/.local/lib/python3.7/site-packages/Crypto/Cipher/ARC4.py", line 119, in <module>
>     key_size = xrange(1,256+1)
> NameError: name 'xrange' is not defined

now i dont know what i can do.

can someone help me?

**Comment by bastelbert** [comment]
Hi, I've got the same error with plugin version 1.2.1.3:
`loxberry@loxberry:~ $ python3 ~/bin/plugins/mirobot2lox-ng/token_extractor.py 
Traceback (most recent call last):
  File "/opt/loxberry/bin/plugins/mirobot2lox-ng/token_extractor.py", line 9, in <module>
    from Crypto.Cipher import ARC4
ModuleNotFoundError: No module named 'Crypto'`

**Comment by mschlenstedt** [comment]
Update to latest version.
