### ISSUE TITLE
0.5.1 error - Python Setuptools installation failed!

### ISSUE THREAD

**Issue by TestMyLox** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#4]
INFO: Starte Script PREROOT.
 INFO: Command: cd "/tmp/uploads/8yyPFt1F1j/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.1" && "/tmp/uploads/8yyPFt1F1j/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.1/preroot.sh" "8yyPFt1F1j" "mirobot2lox-ng" "mirobot2lox-ng" "0.5.1" "/opt/loxberry" "/tmp/uploads/8yyPFt1F1j/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.1"
mode of '/tmp/uploads/8yyPFt1F1j/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.1/preroot.sh' retained as 0755 (rwxr-xr-x)
 INFO: Installation as root user started.
 INFO: Start installing Python Setuptools...
/tmp/uploads/8yyPFt1F1j/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.1/preroot.sh: line 59: pip3: command not found
yes: standard output: Broken pipe
/tmp/uploads/8yyPFt1F1j/LoxBerry-Plugin-MiRobot2Lox-NG-mirobot2lox-ng-0.5.1/preroot.sh: line 61: pip3: command not found
 WARNING: Python Setuptools installation failed!
[8yyPFt1F1j.log](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/2386387/8yyPFt1F1j.log)
 The plugin will not work without.
 WARNING: Giving up.
 CRITICAL: Fehler während der Script-Installation, die Installation wurde beendet.
removed '/tmp/8yyPFt1F1j.zip'

**Comment by mschlenstedt** [comment]
Ah, yes, pip3 is installed after the Python tools are installed. That's the wrong order of course.

**Comment by mschlenstedt** [comment]
Please try: https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/archive/mirobot2lox-ng-0.5.2.zip
