### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MisterDschi** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#41]
I tried different solutions proposed here, but I always end up in the same issue...

Thanks for your help.

Logfile see below:

      no previously-included directories found matching 'docs/_build'
      warning: no previously-included files found matching 'vectors'
      warning: no previously-included files matching '*' found under directory 'vectors'
      warning: no previously-included files matching '*' found under directory '.github'
      warning: no previously-included files found matching 'release.py'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'dev-requirements.txt'
      warning: no previously-included files found matching 'tox.ini'
      warning: no previously-included files found matching 'mypy.ini'
      warning: no previously-included files matching '*' found under directory '.circleci'
      adding license file 'LICENSE'
      adding license file 'LICENSE.APACHE'
      adding license file 'LICENSE.BSD'
      adding license file 'LICENSE.PSF'
      writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
      copying src/cryptography/py.typed -> build/lib.linux-armv7l-cpython-37/cryptography
      creating build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv7l-cpython-37/cryptography/hazmat/bindings/_rust
      running build_ext
      generating cffi module 'build/temp.linux-armv7l-cpython-37/_openssl.c'
      creating build/temp.linux-armv7l-cpython-37
      running build_rust
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      info: syncing channel updates for 'stable-armv7-unknown-linux-gnueabihf'
      info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
      error: 'rustc' is not installed for the toolchain 'stable-armv7-unknown-linux-gnueabihf'
      To install, run `rustup component add rustc`
      /usr/local/lib/python3.7/dist-packages/setuptools/command/build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'cryptography.hazmat.bindings._rust' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'cryptography.hazmat.bindings._rust' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'cryptography.hazmat.bindings._rust' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'cryptography.hazmat.bindings._rust' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust
      
          Python: 3.7.3
          platform: Linux-4.19.118-v7+-armv7l-with-debian-10.6
          pip: 22.1.2
          setuptools: 63.1.0
          setuptools_rust: 1.4.1
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.41.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
yes: standard output: Broken pipe
<WARNING> Python Cryptography tools installation failed! The plugin will not work without.
<WARNING> Giving up.
13.07.2022 20:50:39 <FAIL> Script fails. Installation cannot be continued.
Use of uninitialized value in concatenation (.) or string at /opt/loxberry/sbin/plugininstall.pl line 1810.
Use of uninitialized value in concatenation (.) or string at /opt/loxberry/sbin/plugininstall.pl line 1811
[hLZ6TQC4bX.log](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/9105097/hLZ6TQC4bX.log)
.

**Comment by MisterDschi** [comment]
Hello,

I've used the weekend to setup a completely fresh installation.
Nevertheless I still get an error.

Could somebody please take a look on the included Logfile?

Thank you very much.
[4q7WF1cohU.log](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/9127334/4q7WF1cohU.log)

**Comment by homeconnexde** [comment]
Hi there,

similar error with me. Occured after Loxberry Upgrade from v2 to v3

Seems to be a Version incompatibility with cffi libfifi and cryptography.

Is there any solution or workaround?

THX

[4q7WF1cohU.log](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/11361364/4q7WF1cohU.log)

**Comment by mschlenstedt** [comment]
Try to reinstall.

**Comment by homeconnexde** [comment]
Hi, thx for your reply. Tried reinstalling, also tried deinstall - install, several times.

**Comment by MisterDschi** [comment]
For me it worked after setting up a completely fresh Installation of Loxberry V3.
Then first plugin to install was miROBOT2LOX.

**Comment by homeconnexde** [comment]
Ok I did 

`pip install git+https://github.com/rytilahti/python-miio.git`

Afterwards it worked again.

**Comment by klexi007** [comment]
Ich habe leider auch das Problem, dass die Installation immer abbricht. Ich habe schon mehrmals von vorne begonnen, habe auch die manuelle Installation von python-miio durchgeführt. Hier bekomme ich leider die Fehlermeldung:

ERROR: Package 'python-miio' requires a different Python: 3.7.3 not in '<4.0,>=3.8'

Ich habe danach versucht, python 3.9 zu installieren. Das hat auch geklappt. Allerdings funktioniert die Installation damit auch nicht. Daher bin ich wieder auf 3.7 zurückgegangen.

Ich nutze LoxBerry Version 3.0.0.5. Die Installation des Plugins läuft zu Beginn fehlerfrei, ausgenommen bei der Installation der python-miio tools:
WARNING: Python MIIO tools installation failed! The plugin will not work without.

Gibt es hier einen Workaround oder eine Lösung, damit das Plugin mit Loxberry v3 läuft?

**Comment by mschlenstedt** [comment]
Eigentlich sollte eine höhere Pythonversion installiert sein auf LB3. Was sagt denn "python -V"? Und ist das ein upgegradeter LB2.2? Oder frisch per DietPi installierter LB3?

**Comment by mschlenstedt** [comment]
Keine Antwort - zu.
