### ISSUE TITLE
Integration with Loxone parameters lost

### ISSUE THREAD

**Issue by wbruyland** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#42]
Since a previous Roborock firmware update following points are not correct anymore:
- maintenance
- battery
- cleaning time
- etc
Possible to receive an update?

**Comment by mschlenstedt** [comment]
Ask here: https://github.com/rytilahti/python-miio

If miio supports the device, the plugin can be enhanced. We do not develope the miio software, just build a plugin around.
