### ISSUE TITLE
Update failt

### ISSUE THREAD

**Issue by Wunni73** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#43]
from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
 **WARNING: Python Setuptools installation failed! We will continue anyway.
 INFO: Start installing Python Setuptools...**
Traceback (most recent call last):
File "/usr/local/bin/pip3", line 6, in 
from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
yes: standard output: Broken pipe
Traceback (most recent call last):
File "/usr/local/bin/pip3", line 6, in 
from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
 WARNING: Python Setuptools installation failed! The plugin will not work without.
 WARNING: Giving up.
20:27:23.097 CRITICAL: Script/Command fails. Installation cannot be continued.
20:27:23.098 INFO: Executing command '/usr/bin/sudo -n -u loxberry rm -vf /tmp/wQo0NmBajY.zip 2>&1'...
20:27:23.199 OK: Command executed successfully. - Exitcode 0

**Comment by mschlenstedt** [comment]
Which Loxberry version? Which plugin version? Upgrade or fresh install? Upload the complete logfile of the installation.

Without any information I cannot do nothing.

**Comment by Wunni73** [comment]
Loxberry version 2.2.2.2. 
1.3.0.0 
Neuinstallation oder update ist egal 

Python Setuptools installation failed! 

Python update geht nicht. Die Meldung habe ich auch bei anderen Plugins

**Comment by Wunni73** [comment]
[CgJLOY6C9B.log](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/9941233/CgJLOY6C9B.log)

Hir der Log

**Comment by mschlenstedt** [comment]
Hi,

log Dich bitte per Putty auf dem LoxBerry ein, werde mit dem Befehl "su -" zu root und führe dann mal bitte folgende Befehle aus:

```
python3 -m pip install --upgrade pip
pip3 install -U pip wheel
```

**Comment by Wunni73** [comment]
loxberry@loxberry:~ $ python3 -m pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip
  Downloading https://files.pythonhosted.org/packages/09/bd/2410905c76ee14c62baf69e3f4aa780226c1bbfc9485731ad018e35b0cb5/pip-22.3.1-py3-none-any.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 122kB/s 
Installing collected packages: pip
  The script pip3.10 is installed in '/opt/loxberry/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.3.1
loxberry@loxberry:~ $ pip3 install -U pip wheel
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./.local/lib/python3.7/site-packages (22.3.1)
Collecting wheel
  Downloading https://www.piwheels.org/simple/wheel/wheel-0.38.2-py3-none-any.whl (35 kB)
Installing collected packages: wheel
  WARNING: The script wheel is installed in '/opt/loxberry/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed wheel-0.38.2
loxberry@loxberry:~ $ 

:-( geht immer noch nicht

**Comment by Wunni73** [comment]
[lt59ImCbsa.log](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/9946596/lt59ImCbsa.log)

**Comment by mschlenstedt** [comment]
Du hast als User Loxberry installiert. Du musst als User Root (su -) installieren.

**Comment by Wunni73** [comment]
loxberry@loxberry:~ $ su -
Password: 
su: Authentication failure

**Comment by mschlenstedt** [comment]
Was möchtest du mir damit sagen? Dass du dein Passwort nicht mehr weißt? Es ist das Rootpasswort (Superuser), nicht das Loxberry Passwort.
