### ISSUE TITLE
No module named miio

### ISSUE THREAD

**Issue by MichaKeith** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#45]
Roborock S7
roborock.varuum.a15
Firmware: 4.3.5_1612

/usr/local/bin/miiocli  -o json_pretty roborockvacuum --ip XXX.XXX.XXX.XXX --token XXXXXXXXXXXXXXXXXXXXXX start  2>&1
Output:

Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 5, in <module>
    from miio.cli import create_cli
ModuleNotFoundError: No module named 'miio'

 Der Roboter reagiert nicht auf die Befehle über das PlugIn.

**Comment by mschlenstedt** [comment]
UPdate to latest version.
