### ISSUE TITLE
Can not download Token

### ISSUE THREAD

**Issue by Hansbau** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#46]
With the original bash script from the loxberry plugin  i got the failure issue, curl: (23) Failed writing header.
In this case i try the python sript from Xiaomi-cloud-tokens-extractor. But now i got the failure
Two factor authentication required, please use following url and restart extractor: If i click on the link i got a new pin to varify my
email address and the script closed.

**Comment by mschlenstedt** [comment]
Please ask in the loxone forum
