### ISSUE TITLE
S8 Pro Ultra -> Unknown Model

### ISSUE THREAD

**Issue by Badelo11** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#48]
Thanks for the great pluging.
Unfortunately Model S8 not supported yet -> Unknown model

INFO:miio.cli:Debug mode active
DEBUG:miio.click_common:**Unknown model, trying autodetection. None None**
DEBUG:miio.miioprotocol:Unable to discover a device at address 192.xxx.xxx.xxx
DEBUG:miio.click_common:Exception: Unable to discover the device 192.xxx.xxx.xxx

**Comment by andreas-lackner** [comment]
I have same problem!

The datas received when request status of S8 pro Ultra seem Ok! (attached file)

But no Datas sent to Loxone server


[status.txt](https://github.com/mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG/files/12807715/status.txt)

**Comment by mschlenstedt** [comment]
Ask here: https://github.com/rytilahti/python-miio

If miio supports the device, the plugin can be enhanced. We do not develope the miio software, just build a plugin around.
