### ISSUE TITLE
Support Roborock Q Revo

### ISSUE THREAD

**Issue by lmuser22** [mschlenstedt/LoxBerry-Plugin-MiRobot2Lox-NG#49]
Wäre die Integration vom Roborock A75 (alias Q Revo) möglich?

Device information:

Name(s) of the device: roborock.vacuum.a75
Link: https://us.roborock.com/products/roborock-q-revo

**Comment by mschlenstedt** [comment]
Ask here: https://github.com/rytilahti/python-miio

If miio supports the device, the plugin can be enhanced. We do not develope the miio software, just build a plugin around.
